# Generated by Django 2.1.5 on 2019-03-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
    ]
