# Generated by Django 2.2 on 2020-12-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_page',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
