# Generated by Django 3.1.5 on 2021-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_pages', '0002_flat_page_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_page',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
