# Generated by Django 2.1.5 on 2019-03-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.SlugField(blank=True, default='', unique=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
