# Generated by Django 2.2 on 2020-12-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
    ]
