# Generated by Django 2.1.5 on 2019-08-26 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20190317_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='main_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='food_option',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='rsvp_dinner',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='second_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='STD_sent',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='additional_guests',
            field=models.TextField(default='placeholder', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation_sent',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='no_std',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='rsvp_boat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guest',
            name='total_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_party',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_welcome_dinner',
            field=models.IntegerField(default=0),
        ),
    ]
