# Generated by Django 2.1.5 on 2019-09-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20190826_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='STD_sent',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='invitation_sent',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
