# Generated by Django 2.1.5 on 2019-09-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_auto_20190908_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='guest',
            name='additional_guests',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
