# Generated by Django 2.1.5 on 2019-09-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20190908_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='STD_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='invitation_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
