# Generated by Django 2.2 on 2020-12-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20190908_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='plan_b_PA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='plan_b_chicago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='rsvp_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_boat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_welcome_dinner',
            field=models.BooleanField(default=False),
        ),
    ]
