# Generated by Django 2.2 on 2020-12-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_auto_20201220_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
