# Generated by Django 2.2 on 2020-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_guest_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='plab_b_PA_rsvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='plab_b_chicago_rsvp',
            field=models.BooleanField(default=False),
        ),
    ]
