# Generated by Django 2.2 on 2020-12-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_auto_20201220_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='unknown_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='unknown_guest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
