# Generated by Django 3.1.5 on 2021-01-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_auto_20201220_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
