# Generated by Django 3.1.5 on 2021-01-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_guest_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id_number',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
