# Generated by Django 3.1.5 on 2021-03-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0014_auto_20210302_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='expected_guests',
            field=models.IntegerField(default=0),
        ),
    ]
