# Generated by Django 3.1.5 on 2021-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20210406_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='guests',
            field=models.CharField(max_length=500),
        ),
    ]
