# Generated by Django 3.1.5 on 2021-04-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_auto_20210406_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rsvp',
            field=models.BooleanField(default=False),
        ),
    ]
